if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["balistica_avanzada"] = {
  "Argentina": "Q366-UL0M",
  "Brasil": "AWWC-1TPQ",
  "Canada": "EOQN-128D",
  "Colombia": "DFWT-WO4I",
  "Costa Rica": "HZKQ-OUT7",
  "USA": "LWNS-RITK",
  "Mexico": "78HR-YPUO",
  "Panama": "2H57-CR7K",
  "Peru": "4YUA-Q9LG",
  "Uruguay": "YCI2-EC31",
  "Alemania": "BJV7-EPJZ",
  "Belgica": "NMHK-S44A",
  "Dinamarca": "4WZT-5P5R",
  "Francia": "EZC4-CGAN",
  "Grecia": "T7Z5-YLWX",
  "Holanda": "3COS-OADR",
  "Italia": "H4VY-82QK",
  "Noruega": "WCPQ-0XSH",
  "Portugal": "IESA-GJ5X",
  "Reino Unido": "9E11-L8FO",
  "Rusia": "EZ31-8EVO",
  "Suiza": "E957-M1W0",
  "China": "GYST-W9FN",
  "Corea del Sur": "10QW-WGV8",
  "Filipinas": "5SKO-GWGS",
  "India": "XXOO-4Z9A",
  "Israel": "1T5L-EFDW",
  "Japon": "JNYP-9JJG",
  "Singapur": "CDDE-E2AT",
  "Tailandia": "NWHX-RA16",
  "Turquia": "5QRF-K34Z",
  "Vietnam": "VAN5-ABGW",
  "Arabia": "RGQ7-CRRU",
  "Egipto": "YBOD-OAZD",
  "Kenia": "2G9T-Q5MR",
  "Marruecos": "E15L-UEA5",
  "Nigeria": "CHXP-2U69",
  "Senegal": "7LH2-PCDG",
  "Sudafrica": "U8MZ-DW3Z",
  "Australia": "IE0S-R3NI",
  "Nueva Zelanda": "DMLA-77RK",
  "Malasia": "ROVE-DY4V",
  "Polonia": "6R8C-D23W",
  "Croacia": "8UDX-V6X2",
  "Finlandia": "6L03-19KA"
};