if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["defensa_estructural"] = {
  "Argentina": "S897-52F7",
  "Brasil": "OAYV-LZSZ",
  "Canada": "YBRP-IE9U",
  "Colombia": "X30T-O9AF",
  "Costa Rica": "X0H9-2Q2T",
  "USA": "547E-M7BZ",
  "Mexico": "NQAJ-ECG8",
  "Panama": "W39A-9H0U",
  "Peru": "A9W9-RG7C",
  "Uruguay": "AJSY-HZUL",
  "Alemania": "ZIAM-H9S1",
  "Belgica": "79NU-09W8",
  "Dinamarca": "8UG7-HWFM",
  "Francia": "TSMA-7PR3",
  "Grecia": "B9TM-QV3P",
  "Holanda": "4PSI-CPWT",
  "Italia": "4IM2-48P5",
  "Noruega": "S7QL-XDYD",
  "Portugal": "EX3X-ZAS7",
  "Reino Unido": "L0PL-KQG4",
  "Rusia": "M6EW-C27P",
  "Suiza": "VZ0M-AP25",
  "China": "JIC3-TCEI",
  "Corea del Sur": "VF79-V8TK",
  "Filipinas": "T1FG-RQG7",
  "India": "R9IO-NLZJ",
  "Israel": "4O5O-RTPH",
  "Japon": "IQU3-SR9R",
  "Singapur": "2FI5-O8TL",
  "Tailandia": "RTLX-8REH",
  "Turquia": "4ST0-JVLS",
  "Vietnam": "KTGL-H8CU",
  "Arabia": "XMTE-025A",
  "Egipto": "58G8-B1H9",
  "Kenia": "1UT7-6065",
  "Marruecos": "ZZFO-FSDK",
  "Nigeria": "U86Y-3M1C",
  "Senegal": "SMT7-W6JR",
  "Sudafrica": "GIN2-O0L0",
  "Australia": "UXPH-AM99",
  "Nueva Zelanda": "EFHO-AOLH",
  "Malasia": "6J28-VKN1",
  "Polonia": "EAUB-WNRU",
  "Croacia": "UPF8-VGXT",
  "Finlandia": "A5RF-ET8A"
};