if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["ingenieria_instalaciones"] = {
  "Argentina": "FG54-GB9Z",
  "Brasil": "4HLJ-GKG1",
  "Canada": "XEPV-0MR0",
  "Colombia": "51JY-TGL4",
  "Costa Rica": "84YE-DN77",
  "USA": "23C2-CV0X",
  "Mexico": "OT4L-3IGE",
  "Panama": "KY7N-0J4M",
  "Peru": "WF0L-NH2E",
  "Uruguay": "X9AZ-9UZQ",
  "Alemania": "ED4S-50FM",
  "Belgica": "UWK0-J0EL",
  "Dinamarca": "5OAQ-ATOB",
  "Francia": "RX3D-YIGD",
  "Grecia": "87TG-4P1Z",
  "Holanda": "6J9G-OMAB",
  "Italia": "T7N3-W5U0",
  "Noruega": "G55M-NCNW",
  "Portugal": "UST5-27AK",
  "Reino Unido": "SBRP-0YYM",
  "Rusia": "EZYB-0GA3",
  "Suiza": "DYE5-ZL6Q",
  "China": "QURT-E4FG",
  "Corea del Sur": "ISOB-AYLM",
  "Filipinas": "YD7U-UJAG",
  "India": "T14V-PBC6",
  "Israel": "6I4T-5YA6",
  "Japon": "GIGJ-NY39",
  "Singapur": "636D-X2SQ",
  "Tailandia": "VBA5-KXZC",
  "Turquia": "R2BH-UD1C",
  "Vietnam": "7404-4M8U",
  "Arabia": "K1BM-SQ0E",
  "Egipto": "XEA1-ADA9",
  "Kenia": "612L-NT8O",
  "Marruecos": "T1PN-GW5V",
  "Nigeria": "CIQL-8T3W",
  "Senegal": "DXB3-LA27",
  "Sudafrica": "R0W5-5LNQ",
  "Australia": "HT1Q-4JYD",
  "Nueva Zelanda": "KQVQ-1YNS",
  "Malasia": "IXDJ-7XX1",
  "Polonia": "XPWM-ZG4S",
  "Croacia": "E1ZE-R6DA",
  "Finlandia": "X8XH-09TK"
};