if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["logistica_infraestructura"] = {
  "Argentina": "IQW6-FN90",
  "Brasil": "1V2J-LS5Z",
  "Canada": "IX3V-NB6N",
  "Colombia": "3VFE-9UUH",
  "Costa Rica": "0F7Q-O5Y4",
  "USA": "OK0T-WCEQ",
  "Mexico": "Y71E-K2CO",
  "Panama": "D3QK-JH0D",
  "Peru": "GPQJ-QV42",
  "Uruguay": "19HU-RII8",
  "Alemania": "5DGK-U71U",
  "Belgica": "ZQ9C-9BDI",
  "Dinamarca": "W91T-3K9N",
  "Francia": "0E00-A0WH",
  "Grecia": "QDBH-C27C",
  "Holanda": "YORE-72LX",
  "Italia": "ZJQB-9198",
  "Noruega": "V8PZ-U3XU",
  "Portugal": "5W9K-SGKP",
  "Reino Unido": "DND0-SRFK",
  "Rusia": "3U5R-OPLU",
  "Suiza": "WTXY-22QC",
  "China": "0QKD-A8VJ",
  "Corea del Sur": "5211-LNC0",
  "Filipinas": "4V6Y-03KT",
  "India": "TEPN-ZQ97",
  "Israel": "238Z-15Z5",
  "Japon": "VD19-7JM4",
  "Singapur": "JSAX-091T",
  "Tailandia": "YNWG-S8XI",
  "Turquia": "GLJD-7UF1",
  "Vietnam": "R5F1-9BNN",
  "Arabia": "7GK0-CW0W",
  "Egipto": "CS57-FUDU",
  "Kenia": "DAGE-2K2S",
  "Marruecos": "AIA2-E0FZ",
  "Nigeria": "MJ8K-M3EG",
  "Senegal": "Z6YB-6RJV",
  "Sudafrica": "07EX-YYF9",
  "Australia": "I2B9-J1F4",
  "Nueva Zelanda": "YV96-1X97",
  "Malasia": "TMLC-QRM5",
  "Polonia": "D4MS-1BK5",
  "Croacia": "KRGK-9V33",
  "Finlandia": "XYVL-QBSL"
};