if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["logistica_suministros"] = {
  "Argentina": "ZSSU-KEEL",
  "Brasil": "R40W-FQ2C",
  "Canada": "5I4L-7ZCF",
  "Colombia": "C8W7-WLFD",
  "Costa Rica": "RDHI-P5NS",
  "USA": "E625-IGN7",
  "Mexico": "2LH9-P859",
  "Panama": "C6HE-5RUN",
  "Peru": "YSTI-USSR",
  "Uruguay": "R3HB-Y365",
  "Alemania": "63LA-RB2K",
  "Belgica": "SL3S-NKHV",
  "Dinamarca": "AIBT-8RQL",
  "Francia": "3RLU-DDBU",
  "Grecia": "1HSM-PAND",
  "Holanda": "WA70-O3I1",
  "Italia": "FG0C-1O1D",
  "Noruega": "P8GB-PVDJ",
  "Portugal": "YEMG-UQWC",
  "Reino Unido": "X3YQ-ZFHW",
  "Rusia": "HD94-GCYY",
  "Suiza": "O2JO-XX00",
  "China": "NJ98-9EGJ",
  "Corea del Sur": "MMZG-TC5R",
  "Filipinas": "QDTR-LA6F",
  "India": "KWER-UHCJ",
  "Israel": "OV2H-1FFZ",
  "Japon": "7C13-572Z",
  "Singapur": "835U-M6ZX",
  "Tailandia": "SRJV-J9ZD",
  "Turquia": "W3XP-BQGU",
  "Vietnam": "GAYP-61OP",
  "Arabia": "FPQ8-ULC8",
  "Egipto": "L290-A5PI",
  "Kenia": "ASXB-RWE3",
  "Marruecos": "VJ8O-JU7K",
  "Nigeria": "OID2-H9LY",
  "Senegal": "39PI-WZT8",
  "Sudafrica": "K25X-4F7V",
  "Australia": "H2BX-F5S0",
  "Nueva Zelanda": "DYM5-D7TI",
  "Malasia": "4DVF-0AN5",
  "Polonia": "SA08-WXR5",
  "Croacia": "WOFQ-GSTS",
  "Finlandia": "466Q-W6E2"
};