if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["navegacion_tactica"] = {
  "Argentina": "AHE3-ZL2B",
  "Brasil": "DAMM-VBTS",
  "Canada": "VAUY-6JKU",
  "Colombia": "CVZN-TN7N",
  "Costa Rica": "ZMZA-PETX",
  "USA": "9VL5-Q7V0",
  "Mexico": "N2L4-S6J4",
  "Panama": "CIAM-25UF",
  "Peru": "LLEU-BXME",
  "Uruguay": "6OVQ-SGL3",
  "Alemania": "XZ6U-R6J1",
  "Belgica": "ER9E-QXPO",
  "Dinamarca": "SR8H-JNNJ",
  "Francia": "FXOK-ZV8F",
  "Grecia": "2N1L-XQU0",
  "Holanda": "F5MM-FOJ2",
  "Italia": "KR7B-T8ZK",
  "Noruega": "WLZ6-J1J8",
  "Portugal": "BFAC-D5J3",
  "Reino Unido": "D28G-9JZ8",
  "Rusia": "5MDZ-UFNQ",
  "Suiza": "ENIK-DITK",
  "China": "0K2J-198R",
  "Corea del Sur": "GEKW-VMV1",
  "Filipinas": "HWYF-CJK8",
  "India": "S834-AOCS",
  "Israel": "6UOW-F6NF",
  "Japon": "NH7D-RCOP",
  "Singapur": "5B71-XPYL",
  "Tailandia": "F8UA-NES0",
  "Turquia": "D58Y-BSHK",
  "Vietnam": "YHQ3-K4DC",
  "Arabia": "68MK-MUWP",
  "Egipto": "B857-7YDC",
  "Kenia": "JFAM-ZYLJ",
  "Marruecos": "F253-EQP3",
  "Nigeria": "6P06-2P2D",
  "Senegal": "8810-RILY",
  "Sudafrica": "1NH6-O7S7",
  "Australia": "SSA7-VI91",
  "Nueva Zelanda": "X1PR-GVGK",
  "Malasia": "H75H-KWEJ",
  "Polonia": "2K12-PBF6",
  "Croacia": "9D19-YYT4",
  "Finlandia": "5IYI-L1UJ"
};