if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["ojo_halcon"] = {
  "Argentina": "NXV8-753L",
  "Brasil": "XIDK-1VAN",
  "Canada": "TZIN-7HH3",
  "Colombia": "UJFT-MVP1",
  "Costa Rica": "F713-ACKO",
  "USA": "JH6T-FV33",
  "Mexico": "KKUQ-F0OC",
  "Panama": "MWWV-5OE3",
  "Peru": "L4UN-SZTH",
  "Uruguay": "GFR3-2IDZ",
  "Alemania": "CKE8-1ELX",
  "Belgica": "B6EP-JBKU",
  "Dinamarca": "QQMA-SHFA",
  "Francia": "E35R-W2F6",
  "Grecia": "VKSV-JK5T",
  "Holanda": "IPNO-HDAD",
  "Italia": "ED4N-WZ1X",
  "Noruega": "RBJE-U97B",
  "Portugal": "TZ23-50KK",
  "Reino Unido": "ZD9A-YFRJ",
  "Rusia": "NWAW-9YMV",
  "Suiza": "GUD2-RO1O",
  "China": "UBCE-JI7Z",
  "Corea del Sur": "1BS8-E1EG",
  "Filipinas": "QM18-LQRA",
  "India": "ULVA-TXV3",
  "Israel": "0BXE-Z0G0",
  "Japon": "5EFL-LF2H",
  "Singapur": "RTF6-30M0",
  "Tailandia": "U2B7-4QEW",
  "Turquia": "P6TT-ZNVK",
  "Vietnam": "NJ7D-KHCM",
  "Arabia": "F7FV-QBQ2",
  "Egipto": "UH9G-5GRZ",
  "Kenia": "ZJ1M-YF51",
  "Marruecos": "GUEP-QONT",
  "Nigeria": "FH4C-A3KI",
  "Senegal": "G9KG-BXC0",
  "Sudafrica": "RU55-641C",
  "Australia": "9VX2-J1LS",
  "Nueva Zelanda": "9H4J-94FD",
  "Malasia": "1YXV-81NI",
  "Polonia": "JAHE-CMP7",
  "Croacia": "U47P-VAOK",
  "Finlandia": "9DS5-XK9P"
};