if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["operaciones_internacionales"] = {
  "Argentina": "ZW0X-FTOI",
  "Brasil": "7BZT-BJE3",
  "Canada": "B1HB-HEYL",
  "Colombia": "ZLGO-VJL4",
  "Costa Rica": "ASHN-SBDA",
  "USA": "I63U-PJ1J",
  "Mexico": "WMO6-EJP6",
  "Panama": "OMAV-LDVE",
  "Peru": "U984-L9EG",
  "Uruguay": "CCYI-V6EI",
  "Alemania": "NNS4-1GQ3",
  "Belgica": "2JM9-GGWL",
  "Dinamarca": "1TAG-95OR",
  "Francia": "VAGE-BEIL",
  "Grecia": "X2IB-NG22",
  "Holanda": "LYC0-4KUD",
  "Italia": "WEFL-WCCV",
  "Noruega": "NEVI-UXJW",
  "Portugal": "LTB1-EXM3",
  "Reino Unido": "8XMG-PV4K",
  "Rusia": "WW9D-O4CE",
  "Suiza": "NGZX-NTKX",
  "China": "6YAO-TSX5",
  "Corea del Sur": "AZGC-OLBI",
  "Filipinas": "W9YT-FYOS",
  "India": "ZM4W-TMIY",
  "Israel": "C47Y-TXRQ",
  "Japon": "4IJG-T2XE",
  "Singapur": "OE4B-Z1Z9",
  "Tailandia": "112H-MECY",
  "Turquia": "KVXQ-2DE0",
  "Vietnam": "8M38-GOWL",
  "Arabia": "NVD4-1U7Q",
  "Egipto": "EH76-MOK5",
  "Kenia": "1G9C-1D3I",
  "Marruecos": "3CVZ-4XAK",
  "Nigeria": "4MHQ-55V0",
  "Senegal": "VP0A-ZBLP",
  "Sudafrica": "K8TH-SY94",
  "Australia": "HLPK-QOOD",
  "Nueva Zelanda": "MLP6-Z6CX",
  "Malasia": "XSQA-BOK2",
  "Polonia": "2B9L-HVY8",
  "Croacia": "5HGH-JDPX",
  "Finlandia": "L9JD-K875"
};