if (!window.keysMaster) window.keysMaster = {};
window.keysMaster["sistemas_produccion"] = {
  "Argentina": "G6KI-9W21",
  "Brasil": "31EM-Y30M",
  "Canada": "DXNV-LMN3",
  "Colombia": "WHJC-P386",
  "Costa Rica": "N529-O6IC",
  "USA": "EQNE-U3N0",
  "Mexico": "FIS3-HGQU",
  "Panama": "7HRU-UH8P",
  "Peru": "IDVL-MZGZ",
  "Uruguay": "MXTS-YQ1E",
  "Alemania": "XQ45-IMSG",
  "Belgica": "CWX4-32KK",
  "Dinamarca": "ZTUG-9BF2",
  "Francia": "ZOSM-SO4D",
  "Grecia": "XCD8-41TN",
  "Holanda": "GB1S-NZOI",
  "Italia": "SR6N-3AQZ",
  "Noruega": "WVLX-XIGF",
  "Portugal": "DQ9K-VKXU",
  "Reino Unido": "LITU-2O73",
  "Rusia": "49CO-YY06",
  "Suiza": "P29S-5E1Z",
  "China": "NXX2-YOAK",
  "Corea del Sur": "7GDH-VKS4",
  "Filipinas": "P5WD-BEOD",
  "India": "XTJP-S2PQ",
  "Israel": "A4WH-ARIU",
  "Japon": "PCUF-YW6D",
  "Singapur": "A5KV-XT3V",
  "Tailandia": "0QSB-LRIR",
  "Turquia": "HHNG-4AQK",
  "Vietnam": "7DK5-QSB4",
  "Arabia": "OWYS-KW3S",
  "Egipto": "XPLU-UCD1",
  "Kenia": "FFKD-K29O",
  "Marruecos": "FMRK-YOPI",
  "Nigeria": "ANP9-RMXG",
  "Senegal": "GCCX-INGH",
  "Sudafrica": "L5LA-AXW6",
  "Australia": "WKOK-LUMC",
  "Nueva Zelanda": "RZL9-2F79",
  "Malasia": "U7HI-QA31",
  "Polonia": "HU45-62CM",
  "Croacia": "QWHU-603E",
  "Finlandia": "HSAX-DVT6"
};